<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Computing-Eigenvalues-and-Eigenvectors-with-Numpy" data-toc-modified-id="Computing-Eigenvalues-and-Eigenvectors-with-Numpy-1">Computing Eigenvalues and Eigenvectors with Numpy</a></span></li></ul></div>

# Computing Eigenvalues and Eigenvectors with Numpy

`numpy.linalg.eig` returns two arrays. the first contains the values, the second contains normalized (unit length) right-eigenvectors

`numpy.linalg.eigvals` retuns only the eigenvalues

In [1]:
import numpy as np
import numpy.linalg as npl

In [4]:
A = np.asarray([[3,0],[1,1]])
B = np.asarray([[1,2],[0,1]])
AB = np.asarray([[1,2],[1,3]]) 
BA = np.asarray([[3,2],[1,1]])

In [14]:
npl.eigvals(A)

array([1., 3.])

this means eaigenvalues lambda_1 = 1, lambda_2 = 3

In [15]:
npl.eigvals(B)

array([1., 1.])

In [16]:
npl.eigvals(AB)

array([0.26794919, 3.73205081])

In [17]:
npl.eigvals(BA)

array([3.73205081, 0.26794919])

In [22]:
np.roots([1, -1.4, 0.4])

array([1. , 0.4])

In [23]:
npl.matrix_rank(np.asarray([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]]))

4